services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - '58123:3306'  # 호스트:컨테이너 포트 고정
    restart: always
